[package]
name = "day14-rust"
version = "0.1.0"
authors = ["case <case0x00@protonmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
regex = "1"
itertools = "0.8.0"